### ISSUE TITLE
Recette ne fonctionne pas

### ISSUE THREAD

**Issue by Villard** [vanicat/monde-abonne-recipe#1]
Bonjour
j'ai un compte Le monde
mais la recette ne fonctionne pas. voici l'erreur fournie par calibre. 
Merci
Villard

calibre, version 6.12.0 (win32, embedded-python: True)
Erreur lors de la conversion: Échoué: Récupérer des actualités à partir de Le Monde: Édition abonnés papier

Récupérer des actualités à partir de Le Monde: Édition abonnés papier
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 6.12.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_download_recipe': False,
 'dont_split_on_page_breaks': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000024EC2582DD0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000024EC2582FB0>,
 'page_breaks_before': None,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'transform_html_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: builtin:le_monde_sub_paper
Trying to get latest version of recipe: le_monde_sub_paper
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_recipe
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\recipe_input.py", line 137, in convert
  File "calibre\web\feeds\news.py", line 930, in __init__
  File "<string>", line 72, in get_browser
  File "mechanize\_mechanize.py", line 681, in select_form
mechanize._mechanize.FormNotFoundError: no form matching name 'connection'

**Comment by vanicat** [comment]
Bonjour,

Je n’ai malheureusement plus de compte abonné  à le monde, et donc je ne peux plus tester cette recette. 

Je peux essayer de faire une correction, mais rien ne dit que ça marchera pour la suite.
 
Il faudrait trouver quelqu’un avec des compétences en python et un abonnement au monde pour vraiment corriger ça.

Rémi.

**Comment by Villard** [comment]
Je vais essayer de regarder et corriger.
J'ai déjà corrigé la méthode de connexion, l'URL était correcte mais pas les attributs
avant d'aller plus loin, je vous pose une question. 

Il y une autre recette de sylvain qui télécharge les articles présents sur le site web par rubrique. Or je recherche une recette qui me donnerait plutôt les articles **et seulement ceux** qui sont dans l'édition du journal papier.
J'ai l'impression que c'était l'objectif de votre recette. est-ce bien le cas ?
Merci
Villard

**Comment by vanicat** [comment]
Bonjour,

C’était bien le cas.
J’utilisais pour cela une url (http://medias.lemonde.fr/abonnes/editionelectronique/%Y%m%d/html/%y%m%d.zip) qui contenait un .zip avec une édition électronique du monde. Il faudrait vérifier que ce zip (et cette adresse) fonctionne toujours, ce qui ne me semble pas évident à priori.

Rémi.
